// Generated by CoffeeScript 1.7.1
(function() {
  angular.module('controllers', ['ui.bootstrap']).controller('PaginationCtrl', function($scope) {
    $scope.totalItems = 22;
    $scope.currentPage = 14;
    $scope.itemsPerPage = 1;
    $scope.setPage = function(pageNo) {
      $scope.currentPage = pageNo;
    };
    $scope.pageChanged = function() {
      console.log('Page changed to: ' + $scope.currentPage);
    };
  });

}).call(this);

//# sourceMappingURL=PaginationCtrl.map
